### PR TITLE
updated to v0.3.2

### PR DESCRIPTION
**Pull request by Nicholaswogan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Nicholaswogan** [comment]
@Tobias-Fischer Do you know how I should specify a fortran compiler for windows in the build part of meta.yaml?

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@traversaro - sorry to bother you. I think I remember that you helped with Fortran on Windows somewhere. Do you have a pointer for us to check how this should be done? Currently cmake can't find flang.

**Comment by Tobias-Fischer** [comment]
(even before removing it from the deps)

**Comment by Tobias-Fischer** [comment]
One way of using gfortran on Win is shown in https://github.com/conda-forge/libbezier-feedstock/tree/main/recipe

**Comment by Tobias-Fischer** [comment]
Same trick is used here: https://github.com/conda-forge/capytaine-feedstock/blob/main/recipe/meta.yaml

**Comment by Tobias-Fischer** [comment]
However it seems that the better way is to stick to flang. As there might be incompatibilities when using msys stuff. I had a quick look and @traversaro wrote this CMakeLists for ipopt: https://github.com/conda-forge/ipopt-feedstock/blob/main/recipe/cmake/CMakeLists.txt

There, these seem to be the magic parts:
```cmake
include(CMakeDetermineFortranCompiler)

if (CMAKE_Fortran_COMPILER)
  enable_language(Fortran)
  
  include(FortranCInterface)
  # not sure if all these mangling bits are needed
endif()
```

**Comment by Nicholaswogan** [comment]
@Tobias-Fischer thanks for the suggestions. I adjusted the CMakeLists.txt for numbalsoda so that now it looks like this at the top:

```cmake
cmake_minimum_required(VERSION "3.14")

project(lsoda LANGUAGES CXX C)

include(CMakeDetermineFortranCompiler)
enable_language(Fortran)
include(FortranCInterface)
```

but the conda build still fails:

```sh
-- The Fortran compiler identification is unknown
  CMake Error at CMakeLists.txt:6 (enable_language):
    No CMAKE_Fortran_COMPILER could be found.
```

I should try one the of the hacks you suggest to get gfortran?

**Comment by Tobias-Fischer** [comment]
I think it's best to wait for input from @traversaro - I am not very knowledgeable when it comes to Windows builds ..

**Comment by traversaro** [comment]
I am not sure what is going on, but for sure a difference between this build and ipopt Windows build is that you are using the `Visual Studio 16 2019` CMake generator instead of `NMake Makefiles` (see https://github.com/conda-forge/ipopt-feedstock/blob/74b2d8f809d672e4596f9a68cf5c097873f213cc/recipe/bld.bat#L11). It is just a guess, but it is possible that the classing flang cmake machinery only works with `NMake Makefiles` or `Ninja` .

I am also not an expert of [scikit-build](https://github.com/scikit-build/scikit-build), I wonder if that is interfering with the flang detection in some way.

**Comment by Tobias-Fischer** [comment]
Ok - @Nicholaswogan are you happy to try a direct cmake build here?

**Comment by Nicholaswogan** [comment]
@Tobias-Fischer I would like to first try setting the environment variable `CMAKE_GENERATOR="NMake Makefiles"`, before the install command is called: `"{{ PYTHON }} -m pip install . -vv"`. This might make flang happy.

How can I set this environment variable in meta.yaml?

**Comment by Tobias-Fischer** [comment]
I'd suggest creating a simple bld.bat / build.sh instead of calling pip directly in the meta.yaml

**Comment by Tobias-Fischer** [comment]
That seems to work okay now @Nicholaswogan 

Many thanks for the tip @traversaro

**Comment by Nicholaswogan** [comment]
Yay!!! Thanks so much @Tobias-Fischer. `Bloody Windows` lol.

Can it be merged at this point?

**Pull request merged**
